phishing_keywords = [
    "reset password",
    "verify account",
    "account suspended",
    "update your information",
    "confirm your identity",
    "unauthorized login",
    "payment failed",
    "invoice attached",
    "wire transfer",
    "final notice",
    "security alert",
    "account recovery",
    "re-activate your account",
    "restore access",
    
    "verify email",
    "verify phone number",
    "update details",
    "important update",
    "click to confirm",
    "please verify",
    "verify your identity",
    "unusual activity",
    "billing issue",
    "account verification",
    "action required",
    "confirm payment",
    
    "urgent",
    "suspended",
    "locked",
    "password",
    "login",
    "credentials",
    "billing",
    "invoice",
    "payment",
    "transfer",
    "bank",
    "refund",
    "authorize",
    "attachment",
    "secure",
    "verify"
]